"""new fields in user model

Revision ID: 488c01da3dd8
Revises: 1ca40a3cd38d
Create Date: 2018-04-16 20:16:33.042757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488c01da3dd8'
down_revision = '1ca40a3cd38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
